[package]
name = "wasm-bindgen-runner"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4.5.4", features = ["derive"] }
wasm-bindgen-cli-support = "=0.2.105"

[workspace]
members = []
